service: ukiyonovels-core-component

provider:
  name: aws
  runtime: dotnetcore2.1
  region: us-east-2

package:
  artifact: bin/release/netcoreapp3.0/deploy-package.zip

functions:
  cc:
    handler: UkiyoNovelsCoreComponent::Ukiyo.Handlers.Core.Component.LambdaEntryPoint::FunctionHandlerAsync
    events:
      - http:
          path: /{proxy+}
          method: ANY